---
apiVersion: v1
kind: Secret
metadata:
  name: linkback-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/linkback-backend-gitops
